# Generated by Django 5.0.1 on 2024-01-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tolet_model',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
