# Generated by Django 4.2.4 on 2024-01-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_tolet_model_is_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileprofile',
            name='nid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
